// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD5heaLok4LSxahYZRRJwOCHRt6U5B3Io',
    appId: '1:530531218965:web:1e16c3ebbd3490f916001c',
    messagingSenderId: '530531218965',
    projectId: 'plataforma-profissional',
    authDomain: 'plataforma-profissional.firebaseapp.com',
    storageBucket: 'plataforma-profissional.firebasestorage.app',
    measurementId: 'G-DMKQP60ZX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8p5iEsJ0Uxftmr6QTReqMPb6ZaWMJhM',
    appId: '1:530531218965:android:aa74185b77efaabe16001c',
    messagingSenderId: '530531218965',
    projectId: 'plataforma-profissional',
    storageBucket: 'plataforma-profissional.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD5heaLok4LSxahYZRRJwOCHRt6U5B3Io',
    appId: '1:530531218965:web:747de877c39317ba16001c',
    messagingSenderId: '530531218965',
    projectId: 'plataforma-profissional',
    authDomain: 'plataforma-profissional.firebaseapp.com',
    storageBucket: 'plataforma-profissional.firebasestorage.app',
    measurementId: 'G-GR23T9LKY9',
  );
}
